/**
 * The customer-facing view of campaigns: what's running for me, what I've
 * earned, and — the important one — what WOULD happen if I did the thing I'm
 * about to do.
 *
 * That last question is why the evaluator is pure and lives in `core/`. An offer
 * a customer only discovers after checkout isn't marketing, it's a surprise; and
 * a promise generated by different code than the payout is a promise that
 * eventually drifts. Both the preview here and the payout in `effects.ts` read
 * the same frozen terms through the same functions.
 */
import {
  audienceVerdict,
  campaignIsLive,
  describeEffect,
  evaluateTerms,
  freezeTerms,
  notesForRules,
  summarizeRules,
  type Campaign,
  type CampaignTrigger,
  type OfferPreview,
  type OffersOverview,
  type OfferView,
  type RedemptionView,
  type TriggerFacts,
} from "../../../books-frontend/src/core/config/campaigns";
import type { DiscountItemType } from "../../../books-frontend/src/core/config/discountImpact";
import { getCampaignsConfig, getSparksConfig } from "../appConfig";
import { userFacts } from "./facts";
import { planRefund } from "./refund";
import { ensureEnrollments } from "./events";
import { getEnrollment, listRedemptionsFor } from "./store";

/**
 * Everything the wallet's offers panel needs in one round trip.
 *
 * Calling this ENROLLS the account in anything it now qualifies for, so the
 * frozen promise exists at the moment the customer reads it rather than at the
 * moment they act on it. Reading an offer is the first contact with it.
 */
export async function offersOverview(uid: string): Promise<OffersOverview> {
  const config = await getCampaignsConfig();
  if (!config.enabled) return { enabled: false, offers: [], redemptions: [] };

  const [user, enrollments, redemptions] = await Promise.all([
    userFacts(uid),
    ensureEnrollments(uid),
    listRedemptionsFor(uid, 50),
  ]);
  const enrolledIds = new Set(
    enrollments.filter((e) => !e.holdout).map((e) => e.campaignId),
  );
  const at = Date.now();

  const offers: OfferView[] = [];
  for (const campaign of config.campaigns) {
    // A holdout must never see the offer it's the control group for.
    const enrollment = enrollments.find((e) => e.campaignId === campaign.id);
    if (enrollment?.holdout) continue;

    const enrolled = enrolledIds.has(campaign.id);
    const verdict = audienceVerdict(campaign, user, at);
    // Nothing to say about a campaign they can't join and never could.
    if (!enrolled && !verdict.eligible) continue;

    // An enrolled account reads its FROZEN terms; a prospective one reads live
    // config. That's the whole point of freezing: the promise doesn't move.
    const rules = enrollment
      ? enrollment.terms.rules
      : campaign.rules.filter((r) => r.enabled);
    const summary = enrollment?.terms.summary || summarizeRules(rules);
    if (!summary) continue;

    offers.push({
      campaignId: campaign.id,
      headline: campaign.presentation.headline.trim() || summary,
      subline: campaign.presentation.subline.trim(),
      summary,
      notes: enrollment?.terms.notes?.length
        ? enrollment.terms.notes
        : notesForRules(rules),
      enrolled,
      endsAt: enrollment?.expiresAt || campaign.window.endsAt,
      blockedReason: enrolled ? null : verdict.reason,
    });
  }

  return {
    enabled: true,
    offers: offers.sort((a, b) => Number(b.enrolled) - Number(a.enrolled)),
    redemptions: redemptions.map(toRedemptionView),
  };
}

function toRedemptionView(
  r: Awaited<ReturnType<typeof listRedemptionsFor>>[number],
): RedemptionView {
  return {
    id: r.id,
    campaignId: r.campaignId,
    campaignName: r.campaignName,
    status: r.status,
    summary: r.summary,
    unlocks: r.unlocks,
    at: r.createdAt,
    expiresAt: r.discountExpiresAt > 0 ? r.discountExpiresAt : null,
    used: r.redeemedAt > 0,
    // Customers see WHY something is waiting, but not the internal limit that
    // caused it — "we're checking this by hand" is true and useful; "you hit the
    // daily budget" is neither.
    note:
      r.status === "review"
        ? "We're checking this one — it'll land shortly."
        : null,
  };
}

/**
 * What an imminent action would earn: "this order refunds 240 ✦ to your balance".
 *
 * Deliberately speculative and side-effect free apart from enrollment. It runs
 * the real evaluator against a hypothetical event, so if it says 240 the payout
 * path says 240 too — the numbers come from one implementation.
 */
export async function previewOffers(
  uid: string,
  hypothetical: {
    trigger: CampaignTrigger;
    itemType?: DiscountItemType;
    amount?: number;
    productId?: string;
    projectId?: string;
    surveyId?: string;
  },
): Promise<OfferPreview[]> {
  const out: OfferPreview[] = [];
  try {
    const config = await getCampaignsConfig();
    if (!config.enabled) return out;

    const [user, sparksConfig] = await Promise.all([
      userFacts(uid),
      getSparksConfig(),
    ]);
    const at = Date.now();
    const facts: TriggerFacts = {
      trigger: hypothetical.trigger,
      at,
      itemType: hypothetical.itemType,
      amount: hypothetical.amount,
      productId: hypothetical.productId,
      projectId: hypothetical.projectId,
      surveyId: hypothetical.surveyId,
      // A preview has to assume the purchase clears, or a first-purchase offer
      // would never be previewable to a first-time buyer.
      invoiceNumber: 1,
    };
    // `purchaseCount` is incremented by the event bus before evaluation, so the
    // preview has to model that too or "first purchase" reads false here and true
    // at payout — the exact drift this function exists to prevent.
    const previewUser = { ...user, purchaseCount: user.purchaseCount + 1 };

    for (const campaign of config.campaigns) {
      const enrollment = await getEnrollment(uid, campaign.id);
      if (enrollment?.holdout) continue;
      if (!enrollment && !campaignIsLive(campaign, at)) continue;
      if (!enrollment && !audienceVerdict(campaign, previewUser, at).eligible)
        continue;

      const terms = enrollment?.terms ?? freezeTerms(campaign, at);
      const { matched } = evaluateTerms(terms, previewUser, facts);
      for (const rule of matched) {
        const preview = await previewRule({
          campaign,
          rule,
          uid,
          enrolledAt: enrollment?.enrolledAt ?? at,
          hypothetical,
          sparkValueUsd: sparksConfig.sparkValueUsd,
        });
        if (preview) out.push(preview);
      }
    }
  } catch (err) {
    console.warn("[campaigns] preview failed", err);
  }
  return out;
}

async function previewRule(args: {
  campaign: Campaign;
  rule: Campaign["rules"][number];
  uid: string;
  enrolledAt: number;
  hypothetical: {
    itemType?: DiscountItemType;
    amount?: number;
    projectId?: string;
  };
  sparkValueUsd: number;
}): Promise<OfferPreview | null> {
  const { rule, campaign } = args;

  if (rule.effect.kind === "sparks") {
    return {
      campaignId: campaign.id,
      message: `This earns you ${rule.effect.sparks} Sparks.`,
      sparks: rule.effect.sparks,
    };
  }

  if (rule.effect.kind === "spendRefund") {
    const plan = await planRefund({
      uid: args.uid,
      effect: rule.effect,
      enrolledAt: args.enrolledAt,
      purchasedProjectId: args.hypothetical.projectId ?? null,
      purchaseAmount: args.hypothetical.amount,
      sparkValueUsd: args.sparkValueUsd,
    });
    if (plan.sparks <= 0) return null;
    const worth =
      args.sparkValueUsd > 0
        ? Math.round(plan.sparks * args.sparkValueUsd * 100) / 100
        : 0;
    return {
      campaignId: campaign.id,
      message:
        worth > 0
          ? `This returns ${plan.sparks} Sparks to your balance (about ${worth} back in credit).`
          : `This returns ${plan.sparks} Sparks to your balance.`,
      sparks: plan.sparks,
    };
  }

  if (rule.effect.kind === "purchaseDiscount") {
    return {
      campaignId: campaign.id,
      message: `This earns you ${describeEffect(rule.effect, { plain: true })}.`,
      sparks: 0,
    };
  }

  return null;
}
